"""added feilds to tabkes

Revision ID: 28a2e013f496
Revises: c77559717c27
Create Date: 2024-06-01 17:15:02.427069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a2e013f496'
down_revision = 'c77559717c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movies', sa.String(length=255), nullable=False))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('genres')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_column('movies')

    # ### end Alembic commands ###
